### ISSUE TITLE
Qt6 Version

### ISSUE THREAD

**Issue by complexlogic** [ZXfkSIE/ThousandPlayer#3]
For Linux, the build script requires Qt6.4, which is currently beta. Does any functionality specifically depend on 6.4? I changed it to the current stable version (6.3.1) and it compiled successfully. I would like to use the stable version if possible.

**Comment by ZXfkSIE** [comment]
@complexlogic Nice to see you here!

At present the Qt version is always bumped to the newest due to following reasons:

1. As you can see the player is still in super early development stage. Therefore I don't need to care about the stability. 
2. Actually the development has been started since Qt 6.2.0 Alpha, and I even submitted a little patch to Qt itself to fix a tiny bug. Therefore I tend to use the newest version of Qt so that I can report the bugs to the Qt development team ASAP.
3. There is an important feature comes with Qt Multimedia 6.4 and later: FFmpeg backend. At present Qt still uses different native backends (in Linux, using GStreamer; in Windows, using WMF), which causes some severe problems mainly in Windows. Therefore I am following the newest Qt until the FFmpeg backend becomes available formally.

**Comment by ZXfkSIE** [comment]
Since there are no such problem in Linux, you can of course use older version of Qt in Linux.

**Comment by complexlogic** [comment]
Ok, thanks for clarifying. Looks like an interesting project! Keep up the good work.
